# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iw2p0bZSqrzScIIQJdwg1irdTrIsUE40
"""


import streamlit as st
import torch
import joblib
import numpy as np
from torchvision import models, transforms
from PIL import Image

st.set_page_config(page_title="Jellyfish Classifier")

@st.cache_resource
def load_models():
    base = models.resnet18(weights=None)
    model = torch.nn.Sequential(*list(base.children())[:-1])

    model.load_state_dict(torch.load("resnet18_feature_extractor.pth", map_location="cpu"))
    model.eval()

    svm = joblib.load("svm_classifier.pkl")
    le = joblib.load("label_encoder.pkl")

    return model, svm, le

model, svm, le = load_models()

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3,[0.5]*3)
])

st.title("🪼 Jellyfish Image Classification")

file = st.file_uploader("Upload gambar", type=["jpg","png","jpeg"])

if file:
    img = Image.open(file).convert("RGB")
    st.image(img)

    x = transform(img).unsqueeze(0)

    with torch.no_grad():
        feat = model(x)
        feat = feat.view(feat.size(0), -1).numpy()

        pred = svm.predict(feat)
        label = le.inverse_transform(pred)[0]

    st.success(f"Hasil Prediksi: {label}")
